package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"bookbox/backend/model"
	"bookbox/backend/utils"
	"context"
	"fmt"
)

// ID is the resolver for the id field.
func (r *bookResolver) ID(ctx context.Context, obj *model.Book) (string, error) {
	return obj.ID.String(), nil
}

// PublishedAt is the resolver for the publishedAt field.
func (r *bookResolver) PublishedAt(ctx context.Context, obj *model.Book) (*string, error) {
	if obj.PublishedAt == nil {
		return nil, nil
	}
	dateStr := obj.PublishedAt.In(utils.JST()).Format("2006-01-02")
	return &dateStr, nil
}

// Reviews is the resolver for the reviews field.
func (r *bookResolver) Reviews(ctx context.Context, obj *model.Book) ([]*model.Review, error) {
	panic(fmt.Errorf("not implemented: Reviews - reviews"))
}

// Book returns BookResolver implementation.
func (r *Resolver) Book() BookResolver { return &bookResolver{r} }

type bookResolver struct{ *Resolver }
