package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	model1 "bookbox/backend/graph/model"
	"bookbox/backend/model"
	"bookbox/backend/utils"
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/jinzhu/copier"
)

// CreateBook is the resolver for the createBook field.
func (r *mutationResolver) CreateBook(ctx context.Context, input model1.BookCreateInput) (*model.Book, error) {
	book := &model.Book{}
	copier.Copy(book, &input)

	// publishedAt を変換
	if input.PublishedAt != nil {
		t, err := time.ParseInLocation("2006-01-02", *input.PublishedAt, utils.JST())
		if err != nil {
			return nil, fmt.Errorf("invalid publishedAt format: must be YYYY-MM-DD")
		}
		book.PublishedAt = &t
	}

	if err := r.DB.Create(book).Error; err != nil {
		return nil, err
	}

	return book, nil
}

// UpdateBook is the resolver for the updateBook field.
func (r *mutationResolver) UpdateBook(ctx context.Context, id string, input model1.BookUpdateInput) (*model.Book, error) {
	bookID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid book id: %w", err)
	}

	var book model.Book
	if err := r.DB.First(&book, "id = ?", bookID).Error; err != nil {
		return nil, err
	}

	copier.CopyWithOption(&book, &input, copier.Option{IgnoreEmpty: true, DeepCopy: true})

	// publishedAt を変換
	if input.PublishedAt != nil {
		t, err := time.ParseInLocation("2006-01-02", *input.PublishedAt, utils.JST())
		if err != nil {
			return nil, fmt.Errorf("invalid publishedAt format: must be YYYY-MM-DD")
		}
		book.PublishedAt = &t
	}

	if err := r.DB.Save(&book).Error; err != nil {
		return nil, err
	}

	return &book, nil
}

// DeleteBook is the resolver for the deleteBook field.
func (r *mutationResolver) DeleteBook(ctx context.Context, id string) (bool, error) {
	bookID, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid book id: %w", err)
	}

	if err := r.DB.
		Where("id = ?", bookID).
		Delete(&model.Book{}).Error; err != nil {
		return false, err
	}

	return true, nil
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model1.UserCreateInput) (*model.User, error) {
	user := &model.User{}
	copier.Copy(user, &input)

	if err := r.DB.Create(user).Error; err != nil {
		if strings.Contains(err.Error(), "duplicate key") {
			return nil, fmt.Errorf("email already exists")
		}
		return nil, err
	}

	return user, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, input model1.UserUpdateInput) (*model.User, error) {
	userID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid user id: %w", err)
	}

	var user model.User
	if err := r.DB.First(&user, "id = ?", userID).Error; err != nil {
		return nil, err
	}

	copier.CopyWithOption(&user, &input, copier.Option{IgnoreEmpty: true, DeepCopy: true})

	if err := r.DB.Save(&user).Error; err != nil {
		if strings.Contains(err.Error(), "duplicate key") {
			return nil, fmt.Errorf("email already exists")
		}
		return nil, err
	}

	return &user, nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (bool, error) {
	userID, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid user id: %w", err)
	}

	if err := r.DB.
		Where("id = ?", userID).
		Delete(&model.User{}).Error; err != nil {
		return false, err
	}

	return true, nil
}

// CreateUserBook is the resolver for the createUserBook field.
func (r *mutationResolver) CreateUserBook(ctx context.Context, input model1.UserBookCreateInput) (*model.UserBook, error) {
	userBook := &model.UserBook{}
	copier.Copy(userBook, &input)

	if err := r.DB.Create(userBook).Error; err != nil {
		return nil, err
	}

	return userBook, nil
}

// UpdateUserBook is the resolver for the updateUserBook field.
func (r *mutationResolver) UpdateUserBook(ctx context.Context, id string, input model1.UserBookUpdateInput) (*model.UserBook, error) {
	userBookID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid userbook id: %w", err)
	}

	var userBook model.UserBook
	if err := r.DB.First(&userBook, "id = ?", userBookID).Error; err != nil {
		return nil, err
	}

	copier.CopyWithOption(&userBook, &input, copier.Option{IgnoreEmpty: true, DeepCopy: true})

	if err := r.DB.Save(&userBook).Error; err != nil {
		return nil, err
	}

	return &userBook, nil
}

// DeleteUserBook is the resolver for the deleteUserBook field.
func (r *mutationResolver) DeleteUserBook(ctx context.Context, id string) (bool, error) {
	userBookID, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid userbook id: %w", err)
	}

	if err := r.DB.
		Where("id = ?", userBookID).
		Delete(&model.UserBook{}).Error; err != nil {
		return false, err
	}

	return true, nil
}

// CreateReview is the resolver for the createReview field.
func (r *mutationResolver) CreateReview(ctx context.Context, input model1.ReviewCreateInput) (*model.Review, error) {
	review := &model.Review{}
	copier.Copy(review, &input)

	if err := r.DB.Create(review).Error; err != nil {
		return nil, err
	}

	return review, nil
}

// UpdateReview is the resolver for the updateReview field.
func (r *mutationResolver) UpdateReview(ctx context.Context, id string, input model1.ReviewUpdateInput) (*model.Review, error) {
	reviewID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid review id: %w", err)
	}

	var review model.Review
	if err := r.DB.First(&review, "id = ?", reviewID).Error; err != nil {
		return nil, err
	}

	copier.CopyWithOption(&review, &input, copier.Option{IgnoreEmpty: true, DeepCopy: true})

	if err := r.DB.Save(&review).Error; err != nil {
		return nil, err
	}

	return &review, nil
}

// DeleteReview is the resolver for the deleteReview field.
func (r *mutationResolver) DeleteReview(ctx context.Context, id string) (bool, error) {
	reviewID, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid review id: %w", err)
	}

	if err := r.DB.
		Where("id = ?", reviewID).
		Delete(&model.Review{}).Error; err != nil {
		return false, err
	}

	return true, nil
}

// CreateReviewReaction is the resolver for the createReviewReaction field.
func (r *mutationResolver) CreateReviewReaction(ctx context.Context, input model1.ReviewReactionCreateInput) (*model.ReviewReaction, error) {
	reviewReaction := &model.ReviewReaction{}
	copier.Copy(reviewReaction, &input)

	if err := r.DB.Create(reviewReaction).Error; err != nil {
		return nil, err
	}

	return reviewReaction, nil
}

// DeleteReviewReaction is the resolver for the deleteReviewReaction field.
func (r *mutationResolver) DeleteReviewReaction(ctx context.Context, id string) (bool, error) {
	reviewReactionID, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid reviewreaction id: %w", err)
	}

	if err := r.DB.
		Where("id = ?", reviewReactionID).
		Delete(&model.ReviewReaction{}).Error; err != nil {
		return false, err
	}

	return true, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
