package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"bookbox/backend/model"
	"context"
	"fmt"
)

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	var users []*model.User
	if err := r.DB.Find(&users).Error; err != nil {
		return nil, err
	}
	return users, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	var user model.User
	if err := r.DB.First(&user, "id = ?", id).Error; err != nil {
		return nil, err
	}
	return &user, nil
}

// Books is the resolver for the books field.
func (r *queryResolver) Books(ctx context.Context) ([]*model.Book, error) {
	var books []*model.Book
	if err := r.DB.Find(&books).Error; err != nil {
		return nil, err
	}
	return books, nil
}

// Book is the resolver for the book field.
func (r *queryResolver) Book(ctx context.Context, id string) (*model.Book, error) {
	var book model.Book
	if err := r.DB.First(&book, "id = ?", id).Error; err != nil {
		return nil, err
	}
	return &book, nil
}

// MyBooks is the resolver for the myBooks field.
func (r *queryResolver) MyBooks(ctx context.Context) ([]*model.UserBook, error) {
	// TODO: 認証機能作成後に対応する
	// userID, err := GetUserIDFromContext(ctx)
	// if err != nil {
	// 	return nil, fmt.Errorf("unauthenticated: %w", err)
	// }

	// var books []*model.UserBook
	// if err := r.DB.Where("user_id = ?", userID).Find(&books).Error; err != nil {
	// 	return nil, err
	// }

	// return books, nil
	panic(fmt.Errorf("not implemented: MyBooks - myBooks"))
}

// UserReviews is the resolver for the userReviews field.
func (r *queryResolver) UserReviews(ctx context.Context, userID string) ([]*model.Review, error) {
	var reviews []*model.Review
	if err := r.DB.Where("user_id = ?", userID).Find(&reviews).Error; err != nil {
		return nil, err
	}

	return reviews, nil
}

// BookReviews is the resolver for the bookReviews field.
func (r *queryResolver) BookReviews(ctx context.Context, bookID string) ([]*model.Review, error) {
	var reviews []*model.Review
	if err := r.DB.Where("book_id = ?", bookID).Find(&reviews).Error; err != nil {
		return nil, err
	}

	return reviews, nil
}

// Review is the resolver for the review field.
func (r *queryResolver) Review(ctx context.Context, id string) (*model.Review, error) {
	var review model.Review
	if err := r.DB.First(&review, "id = ?", id).Error; err != nil {
		return nil, err
	}
	return &review, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
