package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"bookbox/backend/model"
	"bookbox/backend/utils"
	"context"
	"fmt"
)

// ID is the resolver for the id field.
func (r *reviewResolver) ID(ctx context.Context, obj *model.Review) (string, error) {
	return obj.ID.String(), nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *reviewResolver) CreatedAt(ctx context.Context, obj *model.Review) (string, error) {
	return utils.FormatJST(&obj.CreatedAt), nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *reviewResolver) UpdatedAt(ctx context.Context, obj *model.Review) (string, error) {
	return utils.FormatJST(&obj.UpdatedAt), nil
}

// Reactions is the resolver for the reactions field.
func (r *reviewResolver) Reactions(ctx context.Context, obj *model.Review) ([]*model.ReviewReaction, error) {
	panic(fmt.Errorf("not implemented: Reactions - reactions"))
}

// ReactionCount is the resolver for the reactionCount field.
func (r *reviewResolver) ReactionCount(ctx context.Context, obj *model.Review) (int32, error) {
	var count int64
	err := r.DB.
		Model(&model.ReviewReaction{}).
		Where("review_id = ?", obj.ID).
		Count(&count).Error

	if err != nil {
		return 0, err
	}

	return int32(count), nil
}

// ID is the resolver for the id field.
func (r *reviewReactionResolver) ID(ctx context.Context, obj *model.ReviewReaction) (string, error) {
	return obj.ID.String(), nil
}

// Review returns ReviewResolver implementation.
func (r *Resolver) Review() ReviewResolver { return &reviewResolver{r} }

// ReviewReaction returns ReviewReactionResolver implementation.
func (r *Resolver) ReviewReaction() ReviewReactionResolver { return &reviewReactionResolver{r} }

type reviewResolver struct{ *Resolver }
type reviewReactionResolver struct{ *Resolver }
