package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	model1 "bookbox/backend/graph/model"
	"bookbox/backend/model"
	"bookbox/backend/utils"
	"context"
	"fmt"
)

// ID is the resolver for the id field.
func (r *userResolver) ID(ctx context.Context, obj *model.User) (string, error) {
	return obj.ID.String(), nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *userResolver) CreatedAt(ctx context.Context, obj *model.User) (string, error) {
	return utils.FormatJST(&obj.CreatedAt), nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *userResolver) UpdatedAt(ctx context.Context, obj *model.User) (string, error) {
	return utils.FormatJST(&obj.UpdatedAt), nil
}

// Books is the resolver for the books field.
func (r *userResolver) Books(ctx context.Context, obj *model.User) ([]*model.UserBook, error) {
	panic(fmt.Errorf("not implemented: Books - books"))
}

// ID is the resolver for the id field.
func (r *userBookResolver) ID(ctx context.Context, obj *model.UserBook) (string, error) {
	return obj.ID.String(), nil
}

// Status is the resolver for the status field.
func (r *userBookResolver) Status(ctx context.Context, obj *model.UserBook) (model1.ReadStatus, error) {
	return model1.ReadStatus(obj.Status), nil
}

// StartedAt is the resolver for the startedAt field.
func (r *userBookResolver) StartedAt(ctx context.Context, obj *model.UserBook) (*string, error) {
	formatted := utils.FormatJST(obj.StartedAt)
	if formatted == "" {
		return nil, nil
	}
	return &formatted, nil
}

// FinishedAt is the resolver for the finishedAt field.
func (r *userBookResolver) FinishedAt(ctx context.Context, obj *model.UserBook) (*string, error) {
	formatted := utils.FormatJST(obj.FinishedAt)
	if formatted == "" {
		return nil, nil
	}
	return &formatted, nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *userBookResolver) CreatedAt(ctx context.Context, obj *model.UserBook) (string, error) {
	return utils.FormatJST(&obj.CreatedAt), nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *userBookResolver) UpdatedAt(ctx context.Context, obj *model.UserBook) (string, error) {
	return utils.FormatJST(&obj.UpdatedAt), nil
}

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

// UserBook returns UserBookResolver implementation.
func (r *Resolver) UserBook() UserBookResolver { return &userBookResolver{r} }

type userResolver struct{ *Resolver }
type userBookResolver struct{ *Resolver }
